### ISSUE TITLE
Getting closer to debris

### ISSUE THREAD

**Issue by GarridoY** [HTML-Earth/P5#30]
Factors:
- Vector from Robot to Debris
- Vector pointing forward from Robot
- \> 90 or > 270 Angle between two before mentioned vectors
- Velocity

Domain = {0, 1}

Check if action (0, 1, 0, 0) exceeds the angle between the two vectors.
If the action is (1, 0, 0, 0) and it is turned away from the debris, it should return 0 else 1
If the action is (0, 0, 0, 0) and the velocity is above 0 and turned towards debris, it should return 1

**Comment by smath17** [comment]
Done in 11359a7
Need to add 2-6 to feature list when using bigger environments
