### ISSUE TITLE
Distance to debris

### ISSUE THREAD

**Issue by GarridoY** [HTML-Earth/P5#33]
Feature:
- Vector between Robot and Debris
- Vector pointing forward from Robot
- Angle between two before mentioned vectors
- Velocity

Domain = {0} U R+ (0 or 1 decimal?)

If the action is (0, 0, 0, 0), the velocity should be considered.

**Comment by rwu17** [comment]
What is the relation between distance from robot to debris and the angle between mentioned vectors? Currently the domain is 0 or any positive real number as the distance to debris, the angle is not used.

**Comment by rwu17** [comment]
The result after implementation of this issue, cannot figure out what is causing this.
![image](https://user-images.githubusercontent.com/33898859/70519251-ece9ff00-1b3b-11ea-9bcc-9a312f818896.png)

**Comment by rwu17** [comment]
Ready to commit? Want to know how to test the feature...

**Comment by rwu17** [comment]
pythagaros, unknown edge of the triangle shall be the domain

**Comment by rwu17** [comment]
ready to close this

**Comment by rwu17** [comment]
How this is implemented by far:
Find robot's next position based on it's current position and velocity, then, from the next position, find the distance to each debris (a total of 6) and return the value of distance.

**Comment by rwu17** [comment]
Reworked:
1.  Based on the certain debris, get its' position
2. Based on the position, find robot's new position
3. Find vector between these two positions and find distance between them
4. Return the distance

**Comment by rwu17** [comment]
Closing this issue and move to either Dropzone or Debris features
