### ISSUE TITLE
Angle to debris

### ISSUE THREAD

**Issue by GarridoY** [HTML-Earth/P5#34]
Feature:
- Vector between Robot and Debris
- Vector from Robot pointing forward
- Angle between two mentioned vectors

Domain = {-180, ..., 180}

**Comment by rwu17** [comment]
How the issue is implemented so far:
Use robot's velocity to predict it's next position, then make a angle between vector to debris and vector pointing straight from robot's new position, and the new angle is returned.

**Comment by rwu17** [comment]
Feature Rework:
1. Based on action, predict Robot's new position using function used in distance to debris feature
2. From robot's new position, find angle between vector from robot to a certain debris and vector pointing forward from robot's rotation.
3. Returns the angle.
