### ISSUE TITLE
Closer to Dropzone

### ISSUE THREAD

**Issue by GarridoY** [HTML-Earth/P5#36]
Factors:
- Vector between Robot and Dropzone
- Vector pointing forward from Robot
- \> 90 or < 270 Angle between two before mentioned vectors
- Velocity

Domain = {0, 1}

If action is (1, 0, 0, 0) and the robot is turned away from the dropzone, return 0
If action is (0, 0, 0, 0), the velocity should be considered.

**Comment by rwu17** [comment]
Most likely solved

**Comment by GarridoY** [comment]
Not solved yet. Program fails to run with this Feature.

getting_closer_to_dropzone is causing the problem.
![Udklip](https://user-images.githubusercontent.com/33898925/70454800-5a018400-1aab-11ea-8daf-35b27618b56e.PNG)

Probably just a missing return statement.

**Comment by rwu17** [comment]
How the issue is implemented by far:
Based on action, check if angle between vector from robot to dropzone and vector pointing forward from robot is within a certain range, return either 0 or 1
