### ISSUE TITLE
Shovel/Arm angle

### ISSUE THREAD

**Issue by smath17** [HTML-Earth/P5#41]
A way for the agent to know where the arm/shovel is, but more so that the agent will know to move the shovel to the ground level before trying to scoop

Factors:
- [ ] Angle of the shovel
- [ ] Angle of the arm

Domain = {0 ,1}

If the arm is not at its lowest angle the action (0, 0, 0? 1?) return 1
Same goes for shovel
Maybe

**Comment by GarridoY** [comment]
Added in 9affc3e
