### ISSUE TITLE
Debris getting closer to Dropzone?

### ISSUE THREAD

**Issue by GarridoY** [HTML-Earth/P5#46]
Domain = {0, 1} or {0} U R+

**Comment by rwu17** [comment]
Thoughts:
- vector from each debris to the dropzone (total of 6)
- distance between each debris to the dropzone (total of 6)

Working on the thoughts

**Comment by rwu17** [comment]
Error occurred after implementation of this issue, the error messages are shown below:
![image](https://user-images.githubusercontent.com/33898859/70610720-559cae80-1c04-11ea-93c0-e0b8aabbf36d.png)

These messages also occurred in issue #33

**Comment by rwu17** [comment]
How this is implemented by far:
Check debris that are in the shovel, predict the robot's next position and distance to the dropzone, if it is getting closer, return true (or 1), else, return false (or 0)
