### ISSUE TITLE
Random Environment: Script to randomly generate environments

### ISSUE THREAD

**Issue by GarridoY** [HTML-Earth/P5#7]
It should only generate:
- Start position of the robot
- Dropzone with a position
- Debris with positions

This could for example happen:
- Everytime the goal is reached
- After a certain amount of times the goal is reached to train the agent more

**Comment by GarridoY** [comment]
Objects:
- Debris
- Dropzone
- Start position

Optional:
- Obstacles
- Rough terrain

**Comment by smath17** [comment]
Debris generation only needs to account for other object position and then it's done
